//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchStringComparison", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.Co" +
        "re")]
    public enum SearchStringComparison : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseInsensitive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseSensitive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HotKeyAndCaseSensitive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchOperator", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.Co" +
        "re")]
    public enum SearchOperator : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnyWord = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TranslationSources", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="TranslationSource")]
    public class TranslationSources : System.Collections.Generic.List<ServiceReference.TranslationSource>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationSource", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Terminology.WebService.Index.En" +
        "tities")]
    public enum TranslationSource : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terms = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UiStrings = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Products", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="Product")]
    public class Products : System.Collections.Generic.List<ServiceReference.Product>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Product : ServiceReference.EntityBase
    {
        
        private int IdField;
        
        private string NameField;
        
        private ServiceReference.Versions VersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Versions Versions
        {
            get
            {
                return this.VersionsField;
            }
            set
            {
                this.VersionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="https://api.terminology.microsoft.com/terminology")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.Version))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.Language))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.Product))]
    public partial class EntityBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Version", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Version : ServiceReference.EntityBase
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Language : ServiceReference.EntityBase
    {
        
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Versions", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="Version")]
    public class Versions : System.Collections.Generic.List<ServiceReference.Version>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Matches", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="Match")]
    public class Matches : System.Collections.Generic.List<ServiceReference.Match>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Match : object
    {
        
        private int ConfidenceLevelField;
        
        private int CountField;
        
        private string DefinitionField;
        
        private string OriginalTextField;
        
        private string ProductField;
        
        private string ProductVersionField;
        
        private System.Nullable<ServiceReference.TranslationSource> SourceField;
        
        private ServiceReference.Translations TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfidenceLevel
        {
            get
            {
                return this.ConfidenceLevelField;
            }
            set
            {
                this.ConfidenceLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this.DefinitionField;
            }
            set
            {
                this.DefinitionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalText
        {
            get
            {
                return this.OriginalTextField;
            }
            set
            {
                this.OriginalTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductVersion
        {
            get
            {
                return this.ProductVersionField;
            }
            set
            {
                this.ProductVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference.TranslationSource> Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Translations Translations
        {
            get
            {
                return this.TranslationsField;
            }
            set
            {
                this.TranslationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Translations", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="Translation")]
    public class Translations : System.Collections.Generic.List<ServiceReference.Translation>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Translation", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Translation : object
    {
        
        private string LanguageField;
        
        private string TranslatedTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslatedText
        {
            get
            {
                return this.TranslatedTextField;
            }
            set
            {
                this.TranslatedTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="https://api.terminology.microsoft.com/terminology")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.MissingParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.InvalidParameters))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.Unexpected))]
    public partial class BaseFault : object
    {
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissingParameter", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class MissingParameter : ServiceReference.BaseFault
    {
        
        private string ParameterNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName
        {
            get
            {
                return this.ParameterNameField;
            }
            set
            {
                this.ParameterNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameters", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class InvalidParameters : ServiceReference.BaseFault
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unexpected", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Unexpected : ServiceReference.BaseFault
    {
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Languages", Namespace="https://api.terminology.microsoft.com/terminology", ItemName="Language")]
    public class Languages : System.Collections.Generic.List<ServiceReference.Language>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Capability", Namespace="https://api.terminology.microsoft.com/terminology")]
    public partial class Capability : object
    {
        
        private bool SupportsAnyToAnyField;
        
        private bool SupportsAnyToEnUsField;
        
        private bool SupportsEnUsToAnyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsAnyToAny
        {
            get
            {
                return this.SupportsAnyToAnyField;
            }
            set
            {
                this.SupportsAnyToAnyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsAnyToEnUs
        {
            get
            {
                return this.SupportsAnyToEnUsField;
            }
            set
            {
                this.SupportsAnyToEnUsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportsEnUsToAny
        {
            get
            {
                return this.SupportsEnUsToAnyField;
            }
            set
            {
                this.SupportsEnUsToAnyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.terminology.microsoft.com/terminology", ConfigurationName="ServiceReference.Terminology")]
    public interface Terminology
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslations", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsUnexp" +
            "ectedFault", Name="Unexpected", Namespace="https://api.terminology.microsoft.com/terminology")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.MissingParameter), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsMissi" +
            "ngParameterFault", Name="MissingParameter", Namespace="https://api.terminology.microsoft.com/terminology")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.InvalidParameters), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetTranslationsInval" +
            "idParametersFault", Name="InvalidParameters", Namespace="https://api.terminology.microsoft.com/terminology")]
        System.Threading.Tasks.Task<ServiceReference.Matches> GetTranslationsAsync(string text, string from, string to, ServiceReference.SearchStringComparison sensitivity, ServiceReference.SearchOperator searchOperator, ServiceReference.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, ServiceReference.Products products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguages", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguagesResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetLanguagesUnexpect" +
            "edFault", Name="Unexpected", Namespace="https://api.terminology.microsoft.com/terminology")]
        System.Threading.Tasks.Task<ServiceReference.Languages> GetLanguagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetProducts", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference.Unexpected), Action="http://api.terminology.microsoft.com/terminology/Terminology/GetProductsUnexpecte" +
            "dFault", Name="Unexpected", Namespace="https://api.terminology.microsoft.com/terminology")]
        System.Threading.Tasks.Task<ServiceReference.Products> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.terminology.microsoft.com/terminology/Terminology/GetCapability", ReplyAction="http://api.terminology.microsoft.com/terminology/Terminology/GetCapabilityRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiceReference.Capability> GetCapabilityAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TerminologyChannel : ServiceReference.Terminology, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TerminologyClient : System.ServiceModel.ClientBase<ServiceReference.Terminology>, ServiceReference.Terminology
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TerminologyClient() : 
                base(TerminologyClient.GetDefaultBinding(), TerminologyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Terminology.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TerminologyClient(EndpointConfiguration endpointConfiguration) : 
                base(TerminologyClient.GetBindingForEndpoint(endpointConfiguration), TerminologyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TerminologyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TerminologyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TerminologyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TerminologyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TerminologyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Matches> GetTranslationsAsync(string text, string from, string to, ServiceReference.SearchStringComparison sensitivity, ServiceReference.SearchOperator searchOperator, ServiceReference.TranslationSources sources, System.Nullable<bool> unique, int maxTranslations, bool includeDefinitions, ServiceReference.Products products)
        {
            return base.Channel.GetTranslationsAsync(text, from, to, sensitivity, searchOperator, sources, unique, maxTranslations, includeDefinitions, products);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Languages> GetLanguagesAsync()
        {
            return base.Channel.GetLanguagesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Products> GetProductsAsync()
        {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Capability> GetCapabilityAsync()
        {
            return base.Channel.GetCapabilityAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Terminology))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Terminology))
            {
                return new System.ServiceModel.EndpointAddress("https://api.terminology.microsoft.com/Terminology.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TerminologyClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Terminology);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TerminologyClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Terminology);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Terminology,
        }
    }
}
