name: Lint Frontend
on:
    push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'Parlance.ClientApp/package.json'
      - name: Restore npm dependencies
        working-directory: Parlance.ClientApp
        run: |
          pnpm install
      - name: Lint
        working-directory: Parlance.ClientApp
        run: |
          pnpm run lint